bachya/aioambient

aioambient/errors.py
aioambient/websocket.py
setup.py
tests/test_websocket.py

This PR updates `python-engineio` to 3.2.2, which fixes socket reconnection issues.
N/A
**Checklist:**

Engineio fix

---

setup.py

aiodns is an optional dependency for aiohttp and it requires C compilation, which does not work on mac. 
Fixes https://github.com/bachya/pyflunearyou/issues/<ISSUE ID>
**Checklist:**

Remove aiodns from requirements

---

Pipfile

`pipenv`'s dependency resolver is struggling with various combinations of `astroid`, `pylint`, `typed-ast` (documented [here](https://github.com/pypa/pipenv/issues/3568) and [here](https://github.com/PyCQA/astroid/issues/639)). This PR pins some dependencies to get things working until `pipenv` comes up with a better solution.
N/A
**Checklist:**

Adjust version pinning to fix Travis

---

setup.py

This PR adjusts `setup.py` in two ways:
1. `python-engineio` must now be version 3.4.4 _or higher_.
2. `python-socketio` must now be version 3.1.2 _or higher_.
N/A
**Checklist:**

Bump versions of python-engineio and python-socketio

---

README.md
aioambient/websocket.py
tests/test_websocket.py

Previously, the websocket API used four handler registration methods for all scenarios, regardless of whether the handler was a method or a coroutine:
```
websocket.on_connect
websocket.on_data
websocket.on_disconnect
websocket.on_subscribed
```
I don't like this, as it's not clear to the implementer of `aioambient` whether a method is registering a method or a coroutine. This PR makes that more explicit:
```
websocket.async_on_connect
websocket.on_connect
websocket.async_on_data
websocket.on_data
websocket.on_disconnect
websocket.async_on_disconnect
websocket.on_subscribed
websocket.async_on_subscribed
```
Additionally, this PR fixes a bug where `on_connect` would fail to await a registered coroutine.
N/A
**Checklist:**

Add explicit async handler methods

---

aioambient/websocket.py

https://github.com/bachya/aioambient/pull/9 added the ability to register either a sync or an async handler for `on_connect`. However, if the user were to call `on_connect`, then later call `async_on_connect` (or vice versa), handlers would exist for _both_ methods. This PR cancels the opposite handler when registering a new one.
N/A
**Checklist:**

Cancel connect handlers appropriately

---

Pipfile
setup.py

This PR bumps `python-engineio` to 3.8.1 and `python-socketio` to 4.1.0. Principally, this solves various reconnection errors.
N/A
**Checklist:**

Bump python-engineio to 3.8.1 and python-socketio to 4.1.0

---

Pipfile
setup.py

This PR bumps the minimum required versions of `python-engineio` to 3.9.3 and `python-socketio` to 4.3.1, respectively.
N/A
**Checklist:**

Bump python-engineio to 3.9.3 and python-socketio to 4.3.1

---

README.md
aioambient/api.py
aioambient/websocket.py
setup.py
tests/test_api.py
tests/test_websocket.py

This PR drops runtime support for Python 3.5.3 and makes the minimum runtime version 3.6. One of a few benefits to follow: we now get to use f-strings.
N/A
**Checklist:**

Switch to f-strings (and remove support for Python 3.5.3)

---

aioambient/api.py
aioambient/client.py
aioambient/const.py
aioambient/websocket.py

Now that we can ensure a minimum of Python 3.6, we can use Python 3.6-style type annotations for variables.
N/A
**Checklist:**

Add Python 3.6-style variable type annotations

---

pyproject.toml

[A recent change in `python-engineio` broke the websocket API that we implement.](https://github.com/miguelgrinberg/python-engineio/issues/152) This PR pins specific versions of it (and `python-socketio`) in place to prevent future issues like this.
https://github.com/bachya/aioambient/issues/21
**Checklist:**

Pin python-engineio and python-socketio to stable versions

---

pyproject.toml
requirements_test.txt

This PR bumps `python-socketio` and `python-engineio` to their latest stable versions (4.5.0 and 3.12.1, respectively).
N/A
**Checklist:**

Bump python-socketio and python-engineio to latest stable versions

---

aioambient/websocket.py
examples/test_websocket.py
pyproject.toml
requirements_test.txt
tests/test_websocket.py

This PR adds a watchdog to the websocket portion of the library – if data doesn't come down every 5 minutes, the connection is closed and re-established. This (combined with some broader exception handling) should help the library reconnect if the Ambient Weather websocket becomes flaky.
N/A
**Checklist:**

Add a websocket watchdog

---

.github/workflows/ci.yaml

#54's use of the `pre-commit` GitHub action unfortunately enforces _all_ hooks, which prevents us from merging PRs to `dev`. This PR keeps the caching from #54, but returns to manually specifying which hooks to run.
N/A
**Checklist:**

Re-introduce manual pre-commit in CI

---

pyproject.toml
requirements_test.txt

This PR unpins specific versions of `python-socketio` and `python-engineio` (and instead merely sets minimum required versions of those libraries).
Fixes https://github.com/bachya/aioambient/issues/64
Fixes https://github.com/bachya/aioambient/issues/65
**Checklist:**

Unpin specific versions of python-socketio and python-engineio

---

aioambient/api.py
aioambient/websocket.py
tests/test_api.py
tests/test_websocket.py

A long time ago, the Ambient devs told me that I should use https://dash2.ambientweather.net instead of https://api.ambientweather.net (as it was deemed more stable). It now looks like https://dash2.ambientweather.net is no longer in service; using https://api.ambientweather.net seems to work fine. So, this PR makes that change.
Fixes https://github.com/bachya/aioambient/issues/68
**Checklist:**

Remove decommissioned API URL

---

.pre-commit-config.yaml
tests/async_mock.py
tests/test_websocket.py

This PR fixes the fact that `asynctest` no longer works in Python 3.8. The PR still ensures that it can be used for Python 3.6 and 3.7.
Fixes https://github.com/bachya/pyopenuv/issues/39
**Checklist:**

Handle asynctest not working in Python 3.8

---

README.md
aioambient/api.py

The docs previously described using a string for the `end_date` parameter (`API.get_device_details`), which isn't correct. This PR fixes the docs (and suggested usage) to properly reflect using a `datetime.date` object.
Fixes https://github.com/bachya/aioambient/issues/78
**Checklist:**

Fix incorrect docs/usage of "end_date" parameter

---

aioambient/client.py
aioambient/const.py
aioambient/websocket.py

This PR ensures that the underlying `python-socketio` and `python-engineio` packages use this package's logger, rather than their own.
N/A
**Checklist:**

Force underlying libraries to use this package's logger

---

aioambient/api.py
aioambient/client.py
aioambient/const.py
aioambient/websocket.py
tests/test_api.py
tests/test_websocket.py

`python-socketio` and `python-engineio` produce their own log messages, which can be confusing when someone is trying to view logs for this application. Since these packages allow for the inclusion of a custom logger, we should do the same so that logs can flow through. This PR accomplishes that.
N/A
**Checklist:**

Allow passing a custom logger to the Client

---

aioambient/api.py
aioambient/websocket.py
tests/test_api.py
tests/test_websocket.py

Per [a recommendation from the Ambient Weather devs](https://github.com/ambient-weather/api-docs/issues/30#issuecomment-954950244), this PR updates the endpoints used for both REST and websocket APIs.
N/A
**Checklist:**

Update REST and websocket APIs to new Ambient Weather endpoints

---

aioambient/util/__init__.py
tests/test_util.py

This PR adds the ability to calculate the public device ID for a MAC address (which is how Ambient structures public dashboard URLs, like `https://ambientweather.net/dashboard/<ID>`.
N/A
**Checklist:**

Add utility to get a public device ID

---

pyproject.toml

We weren't properly enforcing what we already represent: Python 3.7 is the minimum. This PR enforces it.
N/A
**Checklist:**

Ensure Python 3.7 is the minimum version

---

aioambient/websocket.py

The character U+2013 "–" could be confused with the ASCII character U+002d "-", which is more common in source code.
VSCode complains about Unicode characters in HA log files.
**Checklist:**
Small PR, no functional changes.

Replace U+2013 "–" with ASCII character U+002d "-"

---

.pre-commit-config.yaml
aioambient/__init__.py
aioambient/api.py
aioambient/api_request_handler.py
aioambient/errors.py
aioambient/open_api.py
aioambient/util/__init__.py
aioambient/util/climate_utils.py
aioambient/util/location_utils.py
aioambient/websocket.py
examples/test_rest_api.py
examples/test_websocket.py
pyproject.toml
tests/common.py
tests/test_api.py
tests/test_open_api.py
tests/test_util.py
tests/test_websocket.py

This PR uses more of `ruff`'s ruleset, which allows us to (a) be more conforming across the board, (b) eliminate redundant `pylint` and `mypy` checks, and (c) remove several redundant `pre-commit` hooks.
N/A
**Checklist:**

ci: renovate use of `ruff`
